baseURL = "https://barun.cc"
title = "Barun Acharya"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  title = "Hey, I am Barun a.k.a daemon1024 👋"
  footer = "Barun Acharya"
  socialIcons = [
    {name = "github", url = "https://github.com/daemon1024/"},
    {name = "twitter", url = "https://twitter.com/daemon1024/"},
    {name = "linkedin", url = "https://linkedin.com/in/barun-acharya/"},
  ]
  showPostsOnHomePage = "popular"
  metaKeywords = ["blog", "developer", "personal", "daemon1024", "barun"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/daemon1024"
    weight = 5

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 6